### ISSUE TITLE
some problems I met when I build the code by using download models

### ISSUE THREAD

**Issue by leon946** [ma-labo/PromptCharm#5]
Hi author, thanks for your outstanding work. I meet some problems when I build my work.
I download ecco  and daam, I put them into backend but the code can not from daam import trace and can not  from ecco.output import NMF, however it can import ecco.

The other problem is "RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect."

I had tried " CUDA_LAUNCH_BLOCKING=1." and I am sure that I have only one GPU and there is not other proccess running in my GPU.

These two images show problems I had met.
![1](https://github.com/ma-labo/PromptCharm/assets/137180048/a486306a-3aa9-4b8b-8b5a-3e0363a0fd17)
![2](https://github.com/ma-labo/PromptCharm/assets/137180048/143b3808-2b62-4635-8f85-aa81ab9ef099)

Additionly, I use down load stable diffusion v1-4 , gpt2 and Promptist to run the code because I can not link huggingface. These images show the parts I changed to use those local model. Maybe the parts I changed lead to the problems that I met. All of the parts I changed are in main.py.
![3](https://github.com/ma-labo/PromptCharm/assets/137180048/0c84e0f4-9832-4726-a6d2-f0be0bf50cba)
![4](https://github.com/ma-labo/PromptCharm/assets/137180048/870e4662-a5e1-4873-a440-d04febc0635e)
![5](https://github.com/ma-labo/PromptCharm/assets/137180048/1f2b628a-9c07-4f86-809e-c769b7594bf7)

**Comment by paulwong16** [comment]
Hi @leon946 ,

> I download ecco and daam, I put them into backend but the code can not from daam import trace and can not from ecco.output import NMF, however it can import ecco.

For these two modules, you will need to install it by `pip install -e .` within your environment. Otherwise you won't be able to import them as certain modules are not actually linked.

> The other problem is "RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect."

Does your machine have multiple GPUs? In our original implementation, by default, the prompter was run on another GPU (https://github.com/ma-labo/PromptCharm/blob/223fee4d48bc7cefe49432025c9ddd5770069b3c/backend/main.py#L302). So simply change it to `device='cuda:0'` if have only one GPU.

**Comment by leon946** [comment]
It solves my problems. Thank you very much.
